backend:
  name: git-gateway
  branch: main

media_folder: "resimler"
public_folder: "/resimler"

locale: "tr"

collections:

  - name: "sosyoloji"
    label: "Sosyoloji"
    label_singular: "Sosyoloji Yazısı"
    folder: "sosyoloji/yazilar"
    create: true
    slug: "{{slug}}"
    extension: "html"
    path: "{{slug}}/index"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime", format: "DD MMMM YYYY", date_format: "DD MMMM YYYY", time_format: false}
      - {label: "Özet", name: "ozet", widget: "string", required: false}
      - {label: "İçerik", name: "body", widget: "code", default_language: "html", allow_language_selection: false}

  - name: "tarih"
    label: "Tarih"
    label_singular: "Tarih Yazısı"
    folder: "tarih/yazilar"
    create: true
    slug: "{{slug}}"
    extension: "html"
    path: "{{slug}}/index"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime", format: "DD MMMM YYYY", date_format: "DD MMMM YYYY", time_format: false}
      - {label: "Özet", name: "ozet", widget: "string", required: false}
      - {label: "İçerik", name: "body", widget: "code", default_language: "html", allow_language_selection: false}

  - name: "felsefe"
    label: "Felsefe"
    label_singular: "Felsefe Yazısı"
    folder: "felsefe/yazilar"
    create: true
    slug: "{{slug}}"
    extension: "html"
    path: "{{slug}}/index"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime", format: "DD MMMM YYYY", date_format: "DD MMMM YYYY", time_format: false}
      - {label: "Özet", name: "ozet", widget: "string", required: false}
      - {label: "İçerik", name: "body", widget: "code", default_language: "html", allow_language_selection: false}
