backend:
  name: git-gateway
  branch: main

media_folder: "resimler"
public_folder: "/resimler"

collections:
  - name: "yazilar"
    label: "Yazılar"
    folder: "sosyoloji"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Başlık", name: "title", widget: "string"}
      - {label: "Yayın Tarihi", name: "date", widget: "datetime"}
      - {label: "İçerik", name: "body", widget: "markdown"}
